// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYJqv19D6k_drmiyWLWH0UEBy0ihtDMQ0',
    appId: '1:821114857636:web:aca9af3f791e0059d75e31',
    messagingSenderId: '821114857636',
    projectId: 'smrs-77bed',
    authDomain: 'smrs-77bed.firebaseapp.com',
    storageBucket: 'smrs-77bed.firebasestorage.app',
    measurementId: 'G-D7J7JCE087',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-sqXz_0iKROSYHD9-xhFaI1TJOQAmaT0',
    appId: '1:821114857636:android:0d48cf673e4d81f3d75e31',
    messagingSenderId: '821114857636',
    projectId: 'smrs-77bed',
    storageBucket: 'smrs-77bed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3qI5a8yZA-RuzHDk3K-Ani7TZDlIqlfI',
    appId: '1:821114857636:ios:1e05f3a565364dcad75e31',
    messagingSenderId: '821114857636',
    projectId: 'smrs-77bed',
    storageBucket: 'smrs-77bed.firebasestorage.app',
    iosBundleId: 'com.example.smrs',
  );
}
